In [1]:
# ============================================================
# LAB 8 - CATEGORICAL NAIVE BAYES CLASSIFIER
# Play Tennis Dataset
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.naive_bayes import CategoricalNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)


In [3]:
# ============================================================
# Step 1: Load the dataset
# ============================================================

# Change the file name if required
file_path = r"C:\Users\Neethu\Documents\ML\Lab 8.xlsx"

df = pd.read_excel(file_path)

print("Original Dataset")
print(df)

print("\nDataset Shape:", df.shape)

Original Dataset
    No   Outlook Temperature Humidity    Wind Play Tennis
0    1     Sunny         Hot     High    Weak          No
1    2     Sunny         Hot     High  Strong          No
2    3  Overcast         Hot     High    Weak         Yes
3    4      Rain        Mild     High    Weak         Yes
4    5      Rain        Cool   Normal    Weak         Yes
5    6      Rain        Cool   Normal  Strong          No
6    7  Overcast        Cool   Normal  Strong         Yes
7    8     Sunny        Mild     High    Weak          No
8    9     Sunny        Cool   Normal    Weak         Yes
9   10      Rain        Mild   Normal    Weak         Yes
10  11     Sunny        Mild   Normal  Strong         Yes
11  12  Overcast        Mild     High  Strong         Yes
12  13  Overcast         Hot   Normal    Weak         Yes
13  14      Rain        Mild     High  Strong          No
14  15     Sunny        Cool     High    Weak          No
15  16     Sunny        Cool     High  Strong          

In [4]:
# ============================================================
# Step 2: Separate input features and target variable
# ============================================================

X = df[['Outlook', 'Temperature', 'Humidity', 'Wind']]
y = df['Play Tennis']

print("\nInput Features:")
print(X.head())

print("\nTarget Variable:")
print(y.head())



Input Features:
    Outlook Temperature Humidity    Wind
0     Sunny         Hot     High    Weak
1     Sunny         Hot     High  Strong
2  Overcast         Hot     High    Weak
3      Rain        Mild     High    Weak
4      Rain        Cool   Normal    Weak

Target Variable:
0     No
1     No
2    Yes
3    Yes
4    Yes
Name: Play Tennis, dtype: str


In [5]:
# ============================================================
# Step 3: Divide the dataset into training and testing sets
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)



Training Data Shape: (40, 4)
Testing Data Shape: (10, 4)


In [6]:
# ============================================================
# Step 4: Convert categorical values into numerical values
# Using OrdinalEncoder for Categorical Naive Bayes
# ============================================================

encoder = OrdinalEncoder()

X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.transform(X_test)

print("\nEncoded Training Data:")
print(X_train_encoded)

print("\nEncoded Testing Data:")
print(X_test_encoded)



Encoded Training Data:
[[2. 0. 0. 1.]
 [2. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 2. 1. 0.]
 [2. 2. 0. 0.]
 [2. 2. 1. 0.]
 [1. 2. 0. 0.]
 [0. 2. 0. 1.]
 [2. 0. 0. 1.]
 [0. 2. 1. 0.]
 [2. 1. 1. 1.]
 [2. 2. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 1. 0.]
 [2. 1. 1. 0.]
 [1. 1. 0. 1.]
 [2. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 1. 1. 1.]
 [1. 1. 0. 0.]
 [0. 1. 0. 0.]
 [2. 0. 1. 1.]
 [0. 0. 1. 1.]
 [1. 0. 0. 0.]
 [2. 0. 1. 1.]
 [2. 1. 0. 1.]
 [1. 2. 1. 1.]
 [1. 2. 1. 0.]
 [2. 1. 1. 1.]
 [1. 0. 0. 1.]
 [2. 1. 0. 0.]
 [0. 2. 0. 0.]
 [0. 2. 1. 1.]
 [1. 0. 0. 0.]
 [1. 1. 1. 0.]
 [0. 0. 1. 0.]
 [1. 2. 0. 1.]
 [2. 1. 0. 0.]
 [1. 0. 1. 1.]
 [1. 0. 1. 0.]]

Encoded Testing Data:
[[2. 2. 0. 1.]
 [0. 1. 1. 1.]
 [2. 0. 0. 0.]
 [1. 0. 1. 1.]
 [1. 2. 1. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 2. 0. 1.]
 [1. 1. 0. 0.]
 [0. 1. 1. 0.]]


In [7]:
# ============================================================
# Step 5: Train Categorical Naive Bayes model
# ============================================================

nb_model = CategoricalNB()

nb_model.fit(X_train_encoded, y_train)


,"alpha alpha: float, default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"min_categories min_categories: int or array-like of shape (n_features,), default=NoneMinimum number of categories per feature.- integer: Sets the minimum number of categories per feature to `n_categories` for each features.- array-like: shape (n_features,) where `n_categories[i]` holds the minimum number of categories for the ith column of the input.- None (default): Determines the number of categories automatically from the training data... versionadded:: 0.24",None


In [8]:
# ============================================================
# Step 6: Predict class labels for test dataset
# ============================================================

y_pred_nb = nb_model.predict(X_test_encoded)

print("\nNaive Bayes Predictions:")
print(y_pred_nb)


Naive Bayes Predictions:
['Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes']


In [9]:
# ============================================================
# Step 7: Calculate accuracy
# ============================================================

nb_accuracy = accuracy_score(y_test, y_pred_nb)

print("\n======================================")
print("Categorical Naive Bayes Performance")
print("======================================")

print("Accuracy:", nb_accuracy)


Categorical Naive Bayes Performance
Accuracy: 0.9


In [10]:
# ============================================================
# Step 8: Display confusion matrix
# ============================================================

cm_nb = confusion_matrix(
    y_test,
    y_pred_nb,
    labels=['No', 'Yes']
)

print("\nConfusion Matrix:")
print(cm_nb)


Confusion Matrix:
[[2 1]
 [0 7]]


In [11]:
# ============================================================
# Step 9: Display classification report
# ============================================================

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_nb,
        labels=['No', 'Yes']
    )
)



Classification Report:
              precision    recall  f1-score   support

          No       1.00      0.67      0.80         3
         Yes       0.88      1.00      0.93         7

    accuracy                           0.90        10
   macro avg       0.94      0.83      0.87        10
weighted avg       0.91      0.90      0.89        10



In [12]:
# ============================================================
# Step 10: Predict for new weather condition
# ============================================================

new_data = pd.DataFrame({
    'Outlook': ['Sunny'],
    'Temperature': ['Cool'],
    'Humidity': ['High'],
    'Wind': ['Strong']
})

print("\n======================================")
print("New Weather Condition")
print("======================================")

print(new_data)

# Encode new data using the same encoder
new_data_encoded = encoder.transform(new_data)

# Predict class
new_prediction = nb_model.predict(new_data_encoded)

# Predict class probabilities
new_probability = nb_model.predict_proba(new_data_encoded)

print("\nPredicted Class:")
print(new_prediction[0])

print("\nClass Probabilities:")

for class_name, probability in zip(
    nb_model.classes_,
    new_probability[0]
):
    print(class_name, ":", round(probability, 4))


New Weather Condition
  Outlook Temperature Humidity    Wind
0   Sunny        Cool     High  Strong

Predicted Class:
No

Class Probabilities:
No : 0.7894
Yes : 0.2106


In [13]:
# ============================================================
# Step 11: Compare with Decision Tree and Logistic Regression
# ============================================================

# One-hot encoding is used for Decision Tree and
# Logistic Regression because these models work well
# with one-hot encoded categorical features.

onehot_encoder = OneHotEncoder(handle_unknown='ignore')

X_train_onehot = onehot_encoder.fit_transform(X_train)
X_test_onehot = onehot_encoder.transform(X_test)

# ------------------------------------------------------------
# Decision Tree
# ------------------------------------------------------------

dt_model = DecisionTreeClassifier(
    random_state=42
)

dt_model.fit(X_train_onehot, y_train)

y_pred_dt = dt_model.predict(X_test_onehot)

dt_accuracy = accuracy_score(
    y_test,
    y_pred_dt
)

# ------------------------------------------------------------
# Logistic Regression
# ------------------------------------------------------------

lr_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

lr_model.fit(X_train_onehot, y_train)

y_pred_lr = lr_model.predict(X_test_onehot)

lr_accuracy = accuracy_score(
    y_test,
    y_pred_lr
)


In [14]:
# ============================================================
# Step 12: Display comparison
# ============================================================

print("\n======================================")
print("MODEL PERFORMANCE COMPARISON")
print("======================================")

print("Categorical Naive Bayes Accuracy :",
      round(nb_accuracy, 4))

print("Decision Tree Accuracy           :",
      round(dt_accuracy, 4))

print("Logistic Regression Accuracy     :",
      round(lr_accuracy, 4))


MODEL PERFORMANCE COMPARISON
Categorical Naive Bayes Accuracy : 0.9
Decision Tree Accuracy           : 1.0
Logistic Regression Accuracy     : 0.9


In [15]:
# ============================================================
# Step 13: Comparison Table
# ============================================================

comparison = pd.DataFrame({
    'Model': [
        'Categorical Naive Bayes',
        'Decision Tree',
        'Logistic Regression'
    ],
    'Accuracy': [
        nb_accuracy,
        dt_accuracy,
        lr_accuracy
    ]
})

print("\nModel Comparison:")
print(comparison)


Model Comparison:
                     Model  Accuracy
0  Categorical Naive Bayes       0.9
1            Decision Tree       1.0
2      Logistic Regression       0.9


In [16]:
# ============================================================
# Step 14: Display confusion matrices for comparison
# ============================================================

print("\nNaive Bayes Confusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_pred_nb,
        labels=['No', 'Yes']
    )
)

print("\nDecision Tree Confusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_pred_dt,
        labels=['No', 'Yes']
    )
)

print("\nLogistic Regression Confusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_pred_lr,
        labels=['No', 'Yes']
    )
)


Naive Bayes Confusion Matrix:
[[2 1]
 [0 7]]

Decision Tree Confusion Matrix:
[[3 0]
 [0 7]]

Logistic Regression Confusion Matrix:
[[2 1]
 [0 7]]
